### ISSUE TITLE
What bytes exactly do I need to pass to messages.Report.option

### ISSUE THREAD

**Issue by rTiRe** [TelegramPlayGround/pyrogram#111]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

https://telegramplayground.github.io/pyrogram/telegram/functions/messages/report.html

I dont know what bytes exactly do I need to pass here.

why not use reason, as Telegam API suggests: https://core.telegram.org/method/messages.report

Or do I need to at least know in what format to send the bytes in order for Telegram to accept them, because when I try to pass the number to InputReportReasonSpam (https://core.telegram.org/constructor/inputReportReasonSpam) I get this:
```
Telegram says: [400 OPTION_INVALID] - The option specified is invalid and does not exist in the target poll (caused by "messages.Report")
```

code:
```python
await app.session.send(
    Report(
        peer=chat,
        id=[message_id],
        option=InputReportReasonSpam().write(),
        message=report_message,
    ),
)
```
or
```python
await app.session.send(
    Report(
        peer=chat,
        id=[message_id],
        option=b'0x58dbcab8',
        message=report_message,
    ),
)
```

**Comment by SpEcHiDe** [comment]
**The docs in the web page are for an older layer.**

**Comment by rTiRe** [comment]
Exactly what kinds of bytes do I need to pass to messages.Report.option

The docs on the web page will correctly display the information I need (according to layer 192)

**Comment by SpEcHiDe** [comment]
Try `b'1'`

**Comment by rTiRe** [comment]
Thank you so much. Where I can read about other types of options?

**Comment by SpEcHiDe** [comment]
`CAACAgIAAxkBAAJhDGcuO-0Y-PbUzcjSSDw7Ct_RXvvNAAKhLgACcWhwSNw7rJDbK2TRHgQ`
