### ISSUE TITLE
send_media_group() and send_video() question

### ISSUE THREAD

**Issue by fivepe** [TelegramPlayGround/pyrogram#26]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

question1:
app.send_video(xxxxx, "3.M4V")
The video sent cannot be played online
![image](https://github.com/TelegramPlayGround/pyrogram/assets/131561603/518f15c4-9234-4be8-b7e2-a8a4eb1383fa)
but, change file name to "3.mp4"
use app.send_video(xxxxx, "3.mp4")
The video can be played online

### Steps to reproduce

question2:

when the video has m4v file, it run err，show MEDIA_INVALID

### Code example

```python
app.send_video(1320498917, "3.M4V")    
app.send_media_group(
        xxxxxx,
        [
            InputMediaVideo("1.MOV", caption="caption"),
            InputMediaVideo("2.MP4"),
            InputMediaVideo("3.M4V"),
            InputMediaVideo("4.mp4")
        ]
    )
```

### Logs

```shell
Telegram says: [400 MEDIA_INVALID] - Media invalid. (caused by "messages.SendMultiMedia")
Traceback (most recent call last):
  File "C:\Users\HC\env_name\lib\site-packages\pyrogram\dispatcher.py", line 376, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\demo\test\test.py", line 67, in my_handler
    await app1.send_media_group(
  File "C:\Users\HC\env_name\lib\site-packages\pyrogram\methods\messages\send_media_group.py", line 467, in send_media_group
    r = await self.invoke(
  File "C:\Users\HC\env_name\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "C:\Users\HC\env_name\lib\site-packages\pyrogram\session\session.py", line 403, in invoke
    return await self.send(query, timeout=timeout)
  File "C:\Users\HC\env_name\lib\site-packages\pyrogram\session\session.py", line 371, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\HC\env_name\lib\site-packages\pyrogram\errors\rpc_error.py", line 106, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MediaInvalid: Telegram says: [400 MEDIA_INVALID] - Media invalid. (caused by "messages.SendMultiMedia")
```

**Comment by SpEcHiDe** [comment]
[sendVideo](https://core.telegram.org/bots/api#sendvideo), **according to the official documentation** 
> Telegram clients support MPEG4 videos (other formats may be sent as Document)

InputMediaVideo only accepts **video** file_ids any other type of media is expected to raise the MediaInvalid error.

You can figure out how to send M4V as video by looking at [Advanced Usage](https://telegramplayground.github.io/pyrogram/topics/advanced-usage.html), but it is **not recommended**.

**Comment by SpEcHiDe** [comment]
`20613`
