### ISSUE TITLE
UpdateShortMessage bug

### ISSUE THREAD

**Issue by JuiceFW** [TelegramPlayGround/pyrogram#52]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When I try to send a message with reply_markup - reply_markup just doesn't show up.
Without any errors.

### Steps to reproduce

1. Tried to add/remove bot_token from Client.

_P.S. I dont even know what I can do. The code is so simple._

### Code example

```python
item1 = types.InlineKeyboardButton("Do not resend", callback_data=f"!resend_{message.chat.id}")
markup = types.InlineKeyboardMarkup([[item1]])

await app.send_message(
    chat_id=-1002158278968,
    text = "some_text",
    reply_markup=markup
)
```

### Logs

```shell
chat_id = -1002158278968
text="some_text"

reply_markup = {
    "_": "InlineKeyboardMarkup",
    "inline_keyboard": [
        [
            {
                "_": "InlineKeyboardButton",
                "text": "Do not resend",
                "callback_data": "!resend_-1002089543094"
            }
        ]
    ]
}
```

**Comment by SpEcHiDe** [comment]
What is `app.me.is_bot` ?

**Comment by JuiceFW** [comment]
> What is `app.me.is_bot` ?

It is False.

**Comment by SpEcHiDe** [comment]
![image](https://github.com/TelegramPlayGround/pyrogram/assets/6317196/4a63389d-96f8-4e74-bcb5-977948892d0b)

Only bots can send buttons.

**Comment by JuiceFW** [comment]
> ![image](https://private-user-images.githubusercontent.com/6317196/347698512-4a63389d-96f8-4e74-bcb5-977948892d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDUzMjQsIm5iZiI6MTcyMDcwNTAyNCwicGF0aCI6Ii82MzE3MTk2LzM0NzY5ODUxMi00YTYzMzg5ZC05NmY4LTRlNzQtYmNiNS05Nzc5NDg4OTJkMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTMzNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ5MzI5NTAxYWRhODJjNzllNGVkZTI2YzAyMDJmY2EwMjYzY2I0NzgzOTFkMjM4YjNhZmY1NDAwNmQxYjk3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BtwI-_s8Oj2HpQ4E3eELKGy4BIkuUR1-_f4ugvfS9CA)
> 
> Only bots can send buttons.

I tried to add "bot_token" argument to Client and nothing changed. Is there a way to use the client for both the bot and the user?
