### ISSUE TITLE
send InputMediaDocument with thumb parameter 

### ISSUE THREAD

**Issue by anasty17** [TelegramPlayGround/pyrogram#78]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When i use InputMediaVideo to send media group to already uploaded file on telegram(using file_id) it copy also the thumbail. However when i use InputMediaDocument with a doc have thumbnail too using file_id the thumbnail doesn't appear

### Steps to reproduce

Send media group with InputMediaDocument using file_id and already have thumbnails so don't add thumbnail in InputMediaDocument

**Comment by SpEcHiDe** [comment]
Any example code or screenshots? I do not understand what your issue is!

**Comment by anasty17** [comment]
> Any example code or screenshots? I do not understand what your issue is!

inputs = [InputMediaVideo(
                    media=msg.video.file_id, caption=msg.caption
                ), ...]
.reply_media_group(
                media=inputs,
                quote=True,
                disable_notification=True,
            )
            
above example show thubmnails of the videos in media group without filling thumbnail arg in inputmedia

HOWEVER:

InputMediaDocument(
                    media=msg.document.file_id, caption=msg.caption
                )
                it dosn't copy the thumbnail after sending media group

**Comment by SpEcHiDe** [comment]
![20240820_074313](https://github.com/user-attachments/assets/70a256d5-2da0-4c59-ba96-fcf64eb1cab4)


I cannot reproduce. I tried with two documents one which had thumbnail and one which did not have, passing file_id seems to work as expected.

**Comment by anasty17** [comment]
![20240820_053115](https://github.com/user-attachments/assets/bce8c7b2-e006-42a1-a941-c2507ec4423e)
![20240820_053048](https://github.com/user-attachments/assets/f798effb-7ebf-47c6-8c76-737c30692982)

**Comment by SpEcHiDe** [comment]
![20240820_084845](https://github.com/user-attachments/assets/2968d798-eaa3-43f3-a963-ba7760c41955)

now, I am able to reproduce it with WEBM documents. 

for MP4 and MKV documents, thumb parameter is working, issue seems to be with other type of documents.
