### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by fivepe** [TelegramPlayGround/pyrogram#85]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

The following error suddenly occurs when downloading or uploading files, causing the program to be interrupted.

### Steps to reproduce

```
Task exception was never retrieved
future: <Task finished name='Task-24247341' coro=<Session.restart() done, defined at /usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py:244> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 268, in restart
    await self.stop(restart=True)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 205, in stop
    await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
[pyrogram] Client [xxxx_bot] is reconnecting too frequently, sleeping for 18 seconds
```

**Comment by fivepe** [comment]
updated to latest version, this error still occurs

**Comment by SpEcHiDe** [comment]
**I do not get this error in any of my bots**.
